# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddydetail',
            old_name='buddy_name',
            new_name='batch_name',
        ),
        migrations.RemoveField(
            model_name='buddydetail',
            name='batch',
        ),
        migrations.AddField(
            model_name='buddydetail',
            name='assignements',
            field=models.ManyToManyField(blank=True, null=True, to='buddy.Assignment'),
        ),
        migrations.AddField(
            model_name='buddydetail',
            name='batch_day',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buddydetail',
            name='batch_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buddydetail',
            name='batch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BatchDetail',
        ),
    ]
