# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0003_auto_20170205_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddydetail',
            name='batch_time',
            field=models.TimeField(blank=True, help_text='time format is : ', null=True),
        ),
    ]
